from enum import IntEnum


class AppModes(IntEnum):
    ADD_CUSTOM_TEXT = 0
    CHANGE_CASE = 1
    USE_DATETIME = 2
    USE_IMAGE_DIMENSIONS = 3
    USE_PARENT_FOLDER_NAME = 4
    REMOVE_CUSTOM_TEXT = 5
    REPLACE_CUSTOM_TEXT = 6
    ADD_SEQUENCE = 7
    TRUNCATE_FILE_NAME = 8
    CHANGE_EXTENSION = 9


class ItemPosition(IntEnum):
    BEGIN = 0
    END = 1


class ItemPositionExtended(IntEnum):
    BEGIN = 0
    END = 1
    EVERYWHERE = 2


class ItemPositionWithReplacement(IntEnum):
    BEGIN = 0
    END = 1
    REPLACE = 2


class SortSource(IntEnum):
    FILE_NAME = 0
    FILE_PATH = 1
    FILE_SIZE = 2
    FILE_CREATION_DATETIME = 3
    FILE_MODIFICATION_DATETIME = 4
    FILE_CONTENT_CREATION_DATETIME = 5
    IMAGE_WIDTH = 6
    IMAGE_HEIGHT = 7


class TextCaseOptions(IntEnum):
    CAMEL_CASE = 0
    PASCAL_CASE = 1
    SNAKE_CASE = 2
    SNAKE_CASE_SCREAMING = 3
    KEBAB_CASE = 4
    UPPERCASE = 5
    LOWERCASE = 6
    TITLE_CASE = 7


class TruncateOptions(IntEnum):
    REMOVE_SYMBOLS_IN_BEGIN = 0
    REMOVE_SYMBOLS_FROM_END = 1
    TRUNCATE_EMPTY_SYMBOLS = 2


class DateFormat(IntEnum):
    DO_NOT_USE_DATE = 0
    YYYY_MM_DD_TOGETHER = 1
    YYYY_MM_DD_WHITE_SPACED = 2
    YYYY_MM_DD_UNDERSCORED = 3
    YYYY_MM_DD_DOTTED = 4
    YYYY_MM_DD_DASHED = 5
    YY_MM_DD_TOGETHER = 6
    YY_MM_DD_WHITE_SPACED = 7
    YY_MM_DD_UNDERSCORED = 8
    YY_MM_DD_DOTTED = 9
    YY_MM_DD_DASHED = 10
    MM_DD_YYYY_TOGETHER = 11
    MM_DD_YYYY_WHITE_SPACED = 12
    MM_DD_YYYY_UNDERSCORED = 13
    MM_DD_YYYY_DOTTED = 14
    MM_DD_YYYY_DASHED = 15
    MM_DD_YY_TOGETHER = 16
    MM_DD_YY_WHITE_SPACED = 17
    MM_DD_YY_UNDERSCORED = 18
    MM_DD_YY_DOTTED = 19
    MM_DD_YY_DASHED = 20
    DD_MM_YYYY_TOGETHER = 21
    DD_MM_YYYY_WHITE_SPACED = 22
    DD_MM_YYYY_UNDERSCORED = 23
    DD_MM_YYYY_DOTTED = 24
    DD_MM_YYYY_DASHED = 25
    DD_MM_YY_TOGETHER = 26
    DD_MM_YY_WHITE_SPACED = 27
    DD_MM_YY_UNDERSCORED = 28
    DD_MM_YY_DOTTED = 29
    DD_MM_YY_DASHED = 30


class TimeFormat(IntEnum):
    DO_NOT_USE_TIME = 0
    HH_MM_SS_24_TOGETHER = 1
    HH_MM_SS_24_WHITE_SPACED = 2
    HH_MM_SS_24_UNDERSCORED = 3
    HH_MM_SS_24_DOTTED = 4
    HH_MM_SS_24_DASHED = 5
    HH_MM_24_TOGETHER = 6
    HH_MM_24_WHITE_SPACED = 7
    HH_MM_24_UNDERSCORED = 8
    HH_MM_24_DOTTED = 9
    HH_MM_24_DASHED = 10
    HH_MM_SS_AM_PM_TOGETHER = 11
    HH_MM_SS_AM_PM_WHITE_SPACED = 12
    HH_MM_SS_AM_PM_UNDERSCORED = 13
    HH_MM_SS_AM_PM_DOTTED = 14
    HH_MM_SS_AM_PM_DASHED = 15
    HH_MM_AM_PM_TOGETHER = 16
    HH_MM_AM_PM_WHITE_SPACED = 17
    HH_MM_AM_PM_UNDERSCORED = 18
    HH_MM_AM_PM_DOTTED = 19
    HH_MM_AM_PM_DASHED = 20


class DateTimeFormat(IntEnum):
    DATE_TIME_TOGETHER = 0
    DATE_TIME_WHITE_SPACED = 1
    DATE_TIME_UNDERSCORED = 2
    DATE_TIME_DOTTED = 3
    DATE_TIME_DASHED = 4
    REVERSE_DATE_TIME_TOGETHER = 5
    REVERSE_DATE_TIME_WHITE_SPACED = 6
    REVERSE_DATE_TIME_UNDERSCORED = 7
    REVERSE_DATE_TIME_DOTTED = 8
    REVERSE_DATE_TIME_DASHED = 9
    NUMBER_OF_SECONDS_SINCE_JANUARY_1_1970 = 10


class DateTimeSource(IntEnum):
    FILE_CREATION_DATE = 0
    FILE_MODIFICATION_DATE = 1
    CONTENT_CREATION_DATE = 2
    CURRENT_DATE = 3
    CUSTOM_DATE = 4


class ImageDimensionOptions(IntEnum):
    DO_NOT_USE = 0
    WIDTH = 1
    HEIGHT = 2
