from ui.widgets.main.app_modes.add_text_widget import AddTextWidget
from ui.widgets.main.app_modes.change_case_widget import ChangeCaseWidget
from ui.widgets.main.app_modes.change_extension_widget import ChangeExtensionWidget
from ui.widgets.main.app_modes.date_time_widget import DateTimeWidget
from ui.widgets.main.app_modes.image_dimensions_widget import ImageDimensionsWidget
from ui.widgets.main.app_modes.mode_base_widget import ModeBaseWidget
from ui.widgets.main.app_modes.parent_folders_widget import ParentFoldersWidget
from ui.widgets.main.app_modes.remove_text_widget import RemoveTextWidget
from ui.widgets.main.app_modes.replace_text_widget import ReplaceTextWidget
from ui.widgets.main.app_modes.seq_gen_widget import SequenceGeneratorWidget
from ui.widgets.main.app_modes.truncate_text_widget import TruncateTextWidget
